jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/jovyan/Brax-Rodent-Run/serevr_run.py", line 310, in <module>
    make_inference_fn, params, _ = train_fn(environment=env, progress_fn=wandb_progress, policy_params_fn=policy_params_fn)
  File "/opt/conda/lib/python3.10/site-packages/brax/training/agents/ppo/train.py", line 405, in train
    metrics = evaluator.run_evaluation(
  File "/opt/conda/lib/python3.10/site-packages/brax/training/acting.py", line 125, in run_evaluation
    eval_state = self._generate_eval_unroll(policy_params, unroll_key)
  File "/opt/conda/lib/python3.10/site-packages/brax/training/acting.py", line 107, in generate_eval_unroll
    return generate_unroll(
  File "/opt/conda/lib/python3.10/site-packages/brax/training/acting.py", line 75, in generate_unroll
    (final_state, _), data = jax.lax.scan(
  File "/opt/conda/lib/python3.10/site-packages/brax/training/acting.py", line 71, in f
    nstate, transition = actor_step(
  File "/opt/conda/lib/python3.10/site-packages/brax/training/acting.py", line 43, in actor_step
    nstate = env.step(env_state, actions)
  File "/opt/conda/lib/python3.10/site-packages/brax/envs/wrappers/training.py", line 176, in step
    nstate = self.env.step(state, action)
  File "/opt/conda/lib/python3.10/site-packages/brax/envs/wrappers/training.py", line 122, in step
    state = self.env.step(state, action)
  File "/opt/conda/lib/python3.10/site-packages/brax/envs/wrappers/training.py", line 71, in step
    return jax.vmap(self.env.step)(state, action)
  File "/opt/conda/lib/python3.10/site-packages/brax/envs/wrappers/training.py", line 93, in step
    state, rewards = jax.lax.scan(f, state, (), self.action_repeat)
  File "/opt/conda/lib/python3.10/site-packages/brax/envs/wrappers/training.py", line 90, in f
    nstate = self.env.step(state, action)
  File "/home/jovyan/Brax-Rodent-Run/serevr_run.py", line 182, in step
    if distance >= 10:
jax.errors.TracerBoolConversionError: Attempted boolean conversion of traced array with shape bool[]..
The error occurred while tracing the function f at /opt/conda/lib/python3.10/site-packages/brax/envs/wrappers/training.py:89 for scan. This concrete value was not available in Python because it depends on the value of the argument state.metrics['distance_from_origin'].
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerBoolConversionError